# Generated by Django 3.2.3 on 2021-07-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_served', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('request_type', models.CharField(choices=[('speak', 'speak'), ('order', 'order'), ('privilege', 'privilege')], max_length=50)),
                ('participant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_request', to='speakers.participant')),
            ],
        ),
    ]
