# Generated by Django 3.2.3 on 2021-07-17 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0003_auto_20210717_1426'),
        ('organisations', '0002_memberrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='motion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motion_meeting', to='motions.motion'),
        ),
    ]
