# Generated by Django 3.2.3 on 2021-07-17 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_meeting_motion'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrequests',
            name='meeting',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_member_requests', to='organisations.meeting'),
        ),
    ]
