# Generated by Django 3.2.3 on 2021-07-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_memberrequests_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='joinees',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
