# Generated by Django 3.2.3 on 2021-07-21 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_auto_20210721_1731'),
        ('motions', '0003_auto_20210717_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballot', to='speakers.participant', verbose_name='proposer'),
        ),
    ]
